### PR TITLE
fix: make theme customization of ``config.json`` dynamic

### PR DESCRIPTION
**Pull request by vaab**
Prior to this, ``config.json`` theme customization was baked in CSS at
build time. To ensure that we can release a unique release with the
build artifacts, that can still be configured through the
``config.json``, we need to load the CSS variables dynamically.

Signed-off-by: Valentin Lab <valentin.lab@kalysto.org>

### CODE REVIEW

**Comment by vaab** [comment]
I have not yet tested the creation of mobile apps, and this will need to be done.

**Comment by seegwen** [comment]
Do you mean that you want to have only one build for each os and deploy monujo,pive,roue with the same build ?
Is that your plan ?

**Comment by vaab** [comment]
Sorry for the late answer.

Yes, having a unique release package for the web makes a lot of sense for deployment and release ease: we can propose a single package for each version. On mobile version for now, we need to bake in the `config.json` and this is still a nice option to have this last configuration part to be baked in thanks to a simple file change... (this now need to be done after `npm run build`) even if I understand that we still have to have a version per currencies in our current situation, the build is not anymore a required step to make each versions.

This also let us free to move to a probable demand in a possible future: having the `config.json` stored on the server side (this is also what `biletujo` does). This would allow to have a single app ready to use on any server and customized per-server.

Also, it was a little un-natural to have some part of the `config.json` being dynamical and other not.

**Review by stephansainleger — APPROVED** [review]
Functional Test OK

**Comment by seegwen** [comment]
Thanks for the detailed explaination.

**Review by seegwen — APPROVED** [review]

**Pull request merged**
